services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Iresults\ResizeImageError\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Iresults\ResizeImageError\Command\ImageResizeCommand:
    tags:
      - name: imagestuff
        command: 'resize-image-error:image-resize'
        description: 'Test something'
